services:
  bukinator-db:
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'innodb'
      MYSQL_ROOT_PASSWORD: 'asdf'
    ports:
      - '3306:3306'
    expose:
      - '3306'