server:
  port: 8081
spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/bukinator
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  batch:
    jdbc:
      initialize-schema: always