spring:
  active: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/innodb?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: asdf
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
