spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myrealtrip_virtual_number?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: password

  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        globally_quoted_identifiers: true